const ROUTES = {
  entry: 'pages/entry/index',
  guestHome: 'pages/home/guest/index',
  login: 'pages/login/index',
  loginInvite: 'pages/login/invite/index',
  loginForgot: 'pages/login/forgot/index',
  home: 'pages/home/index',
  homeOther: 'pages/home-other/index',
  playerHome: 'pages/home/player/index',
  expertHome: 'pages/home/expert/index',
  guideHome: 'pages/home/guide/index',
  roleApply: 'pages/role/apply/index',
  roleStatus: 'pages/role/status/index',
  gameHall: 'pages/game/hall/index',
  gameCreate: 'pages/game/create/index',
  gameDetail: 'pages/game/detail/index',
  gameAudit: 'pages/game/audit/index',
  gameAuditDetail: 'pages/game/audit-detail/index',
  gameGreet: 'pages/game/greet/index',
  gameGuideChat: 'pages/game/guide-chat/index',
  gameGuideProgress: 'pages/game/guide-progress/index',
  gameGuideProgressDetail: 'pages/game/guide-progress-detail/index',
  gameShare: 'pages/game/share/index',
  gameInvite: 'pages/game/invite/index',
  gamePayment: 'pages/game/payment/index',
  gameApplications: 'pages/game/applications/index',
  gameDelivery: 'pages/game/delivery/index',
  gameReview: 'pages/game/review/index',
  map: 'pages/map/index',
  message: 'pages/message/index',
  imRoom: 'pages/im/room/index',
  profile: 'pages/profile/index',
  profileMember: 'pages/profile/member/index',
  profileAchievements: 'pages/profile/achievements/index',
  metaverse: 'pages/placeholder/metaverse/index'
}

module.exports = {
  ROUTES
}
